FROM ubuntu:rolling

ARG DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-euxo", "pipefail", "-c"]

RUN apt-get update; \
    apt-get full-upgrade -y; \
    apt-get install -y --no-install-recommends \
        apt-transport-https \
        ca-certificates \
        curl \
        git \
        gnupg \
        locales \
        lsb-release \
        openssl \
        python3 \
        python3-apt \
        python3-dev \
        python3-pip \
        python3-setuptools \
        tar \
        xz-utils \
    ;\
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Run this container as current host user:
ARG USER_ID
ARG GROUP_ID
RUN groupadd -g "${GROUP_ID}" docker; \
    useradd -l -u "${USER_ID}" -g docker docker; \
    install -d -m 0750 -o docker -g docker /home/docker; \
    chown "${USER_ID}":"${GROUP_ID}" -R /home/docker

WORKDIR /tmp/

# nodejs LTS and latest NPM:
RUN curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n \
    -o /usr/local/bin/n; \
    chmod 0755 /usr/local/bin/n; \
    n lts; \
    npm install -g npm@latest

# shellcheck:
ARG SHELLCHECK_VERSION=0.7.2
RUN curl -OfsSL \
    "https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz"; \
tar -xf "shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz"; \
mv "shellcheck-v${SHELLCHECK_VERSION}/shellcheck" /usr/local/bin/; \
rm -r \
    "shellcheck-v${SHELLCHECK_VERSION}/" \
    "shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz"

# hadolint:
ARG HADOLINT_VERSION=2.7.0
RUN curl -fsSL \
        "https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-x86_64" \
        -o /usr/local/bin/hadolint; \
    chmod +x /usr/local/bin/hadolint

# Docker:
RUN curl -fsSL \
        https://download.docker.com/linux/ubuntu/gpg | \
        gpg --dearmor > /usr/share/keyrings/docker.gpg; \
    echo \
        "deb \
        [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable" > /etc/apt/sources.list.d/docker.list; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        docker-ce \
        docker-ce-cli \
        containerd.io \
    ;\
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

# editorconfig-checker (ec):
ENV EC_VERSION 2.3.5
RUN curl -OfsSL \
        "https://github.com/editorconfig-checker/editorconfig-checker/releases/download/${EC_VERSION}/ec-linux-amd64.tar.gz"; \
    tar -xzf ec-linux-amd64.tar.gz; \
    mv bin/ec-linux-amd64 /usr/local/bin/ec; \
    rm -r \
        ec-linux-amd64.tar.gz \
        bin/

# Trivy:
RUN curl -fsSL \
        https://aquasecurity.github.io/trivy-repo/deb/public.key | \
        gpg --dearmor > /usr/share/keyrings/trivy.gpg; \
    echo \
        "deb \
        [signed-by=/usr/share/keyrings/trivy.gpg] \
        https://aquasecurity.github.io/trivy-repo/deb bionic main" \
        > /etc/apt/sources.list.d/trivy.list; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        trivy \
    ;\
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip:
RUN pip3 install --upgrade --no-cache-dir \
        pip \
        setuptools \
        wheel \
    ; \
    apt-get remove -y \
        python3-pip \
        python3-setuptools \
        python3-wheel \
    ; \
    apt-get autoremove -y

USER docker

ENV PATH="/home/docker/.local/bin:${PATH}"

# pip (common):
COPY requirements.txt /tmp/
RUN pip3 install --upgrade --no-cache-dir --requirement /tmp/requirements.txt

WORKDIR /docker

CMD ["bash"]
